- name: Ensure sources.list are proeprly defined (debian.net)
  copy: >
    src=etc/apt/sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644
  notify: apt update

- name: Ensure system is upgraded (It can take a long time)
  apt: upgrade=yes

- name: Ensure proper system variables are setting
  sysctl: name=net.ipv4.ip_forward value=1 state=present